accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('recipe/', views.recipe, name='recipe'),
    path('single/', views.single, name='single'),
    path('single1/', views.single1, name='single1'),
    path('profile/<int:pk>/', views.ProfileDetailView.as_view(), name='profile'),
    # path('profile/<int:pk>/edit/', views.profile_update, name='edit_profile'),
]

heart_disease_prediction/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path

from accounts import views
from heart_disease_prediction import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.user_login, name='user_login'),
    path('accounts/', include('accounts.urls')),
    path('predict/', include('predict_risk.urls')),
    path('predict_1/', include('predict_risk_1.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predict_risk/urls.py
from django.urls import re_path
from . import views

app_name = 'predict'

urlpatterns = [
    re_path(r'^(?P<pk>\d+)$', views.PredictRisk, name='predict'),
]

predict_risk_1/urls.py
from django.urls import re_path
from . import views

app_name = 'predict_1'

urlpatterns = [
    re_path(r'^(?P<pk>\d+)$', views.PredictRisk_1, name='predict_1'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_pic = models.ImageField(upload_to='profile_pics', default="1.jpg")

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('profile', args=[str(self.user.id)])

accounts/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Kullanıcı Adı'}
    ), required=True, max_length=50)

    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Email Giriniz'}
    ), required=True, max_length=50)

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Şifre'}
    ), required=True, max_length=50)

    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Şifre Onay'}
    ), required=True, max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "Şifre ve Onay Şifresi Uyuşmuyor"
            )


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        widgets = {'username': forms.TextInput(attrs={'readonly': 'True'})}

accounts/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm, UpdateProfileForm
from django.views.generic import DetailView,UpdateView,TemplateView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import UserProfileInfo, User
from django.shortcuts import get_object_or_404
# Create your views here.

flag=False

@login_required
def user_logout(request):
    #del request.session['user_id']
    request.session.flush()
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))

def recipe(request):
    return render(request, 'accounts/recipe.html')

def single(request):
    return render(request, 'accounts/single.html')

def single1(request):
    return render(request, 'accounts/single1.html')    

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

        if registered:
            return HttpResponseRedirect(reverse('user_login'))

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'accounts/register.html',{'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    global flag

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        switch = request.POST.get('switch')
        if (switch)=="Kalp":
            flag=True
        else:
            flag=False

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                request.session['user_id'] = user.profile.pk

                if (switch) == 'Kalp':
                    return HttpResponseRedirect(reverse('predict:predict', kwargs={'pk': user.profile.pk}))
                elif (switch) == 'Böbrek':
                    return HttpResponseRedirect(reverse('predict_1:predict_1', kwargs={'pk': user.profile.pk}))
                else:
                    return render(request, 'accounts/login.html', {})

            else:
                return HttpResponse("Hesap aktif değil")
        else:
            print("Tried login and failed")
            print("username: {} and password: {}".format(username, password))
            return HttpResponse("Geçersiz giriş bilgileri sağlandı!")

    else:
        return render(request, 'accounts/login.html', {})

class ProfileDetailView(LoginRequiredMixin, DetailView):
    login_url = '/'
    redirect_field_name = '/'
    model = UserProfileInfo
    template_name = 'accounts/profileview.html'

    def get_context_data(self, **kwargs):
        if self.request.session.has_key('user_id'):
            u_id = self.request.session['user_id']
            context = super(ProfileDetailView, self).get_context_data(**kwargs)
            context['user_id'] = u_id
            context['flag']=flag

        return context

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="tr">
<head>
    <meta charset="utf-8">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style3_1.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
    <title>Tahmin Sistemi</title>
</head>
<body style="background-image: url('{% static 'images/2.jpg' %}')">
	<!-- main -->
	<div class="agileits-main">
		<div class="w3top-nav">

				<div class="w3top-nav-left">
					<h1 style="color:white;">Kalp Ve Böbrek Hastalığı Tahmin Sistemi</h1>
				</div>

				<div class="w3top-nav-right">
					<ul>

						<li><a class="button" href="{% url 'accounts:register' %}">Üye Ol</a></li>
						<li><a class="button" href="/admin">Yönetici Girişi</a></li>
					</ul>
				</div>

		</div>

    <div class="header-main">
      {%if user.is_authenticated %}
        <h2>Zaten giriş yaptınız !!</h2>
        <button class="btn btn-neutral"><a href="{% url 'accounts:logout'%}">Çıkış Yap</a></button>
      {%else%}
    <h3>Giriş Yap</h3>
			<div class="header-bottom">
				<div class="header-right w3agile">
					<div class="header-left-bottom agileinfo">
            <form role="form" action=" {% url 'user_login' %}" method="post">
            {% csrf_token %}
							<div class="icon1">
								<input type="text" name="username" placeholder="Kullanıcı Adı" >
							</div>
							<div class="icon1">
								<input type="password"  name="password" placeholder="Şifre"/>
							</div>
				               <div class="icon1">
								   <input type="text" name="switch" placeholder="Kalp/Böbrek">
								</div>
							<div class="bottom">
								<input type="submit" value="Giriş Yap">
							</div>
					</form>&nbsp;

					</div>
				</div>
			</div>
	</div>

	</div>
	<!-- //main -->
  {% endif %}
</body>

</html>

accounts/templates/accounts/profileview.html
<!DOCTYPE html>
{% load static %}
<html lang="tr">
<head>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />


    <meta charset="UTF-8">
    <title>Tahmin Sistemi</title>

</head>

<body class="profile-page sidebar-collapse">
 <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent" color-on-scroll="400" >
        <div class="container">
            <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="">
                <ul class="nav nav-tabs" data-tabs="tabs">


                    <li class="nav-item">
                        {% if flag %}
                        <a href="{% url 'predict:predict' pk=user_id %}" class="btn btn-neutral">Tahmin</a>
                        {%else%}
                        <a href="{% url 'predict_1:predict_1' pk=user_id %}" class="btn btn-neutral">Tahmin</a>
                        {%endif%}
                    </li>
                    <li class="nav-item">
                      <a href="{% url 'accounts:logout'%}"  class="btn btn-neutral">Çıkış Yap</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="wrapper">
        <div class="page-header page-header-small" filter-color="orange" style="max-height: 100px;">
            <div class="page-header-image" data-parallax="true" style="background-image: url('{% static 'img/image1.jpg' %}'); ">
            </div>
            <div class="container">
                <div class="content-center">
                    <div class="photo-container">
                        <img src="{{userprofileinfo.profile_pic.url}}" />
                    </div>
                    <h3 class="title">{{ userprofileinfo.user.username }}</h3>
                    <p class="h5">{{ userprofileinfo.user.email }}</p>


                    </div>
                </div>
            </div>
        </div>

    <div class="section">
            <div class="container">
                <div class="button-container">

                        <i class="fa fa-user-circle"></i>
                    </a>

                </div>
            </div>
    </div>
    <div class="container">
    <div class="card-header bg-warning btn-round text-white">Tahminler</div>
        <hr>


        {% for pred in userprofileinfo.predict.all  %}
            <br>

             <div class="card card-login" style="width: 100%">
                    <div class="card-header bg-dark text-white" style="height: 50px;"> Tahmin : {{ pred.num|safe}}
                    </div>
                    <div class="container">
                        <br>
                        <p>Yaş: {{pred.age}}</p>
                        <p>Cinsiyet: {{pred.sex}}</p>
                    </div>
                    <div class="card-footer bg-light" >Tahmin Tarihi {{ pred.predicted_on }}</div>

            </div>
            <br>
        {% endfor %}


    </div>

</body>
<script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap_ui_kit.js' %}" type="text/javascript"></script>
</html>

accounts/templates/accounts/recipe.html
<!DOCTYPE html>
{% load static %}
<html lang="tr">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Diyetisyen | Tarifler</title>
		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|" rel="stylesheet" type="text/css">
		<link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'fonts/iconmoon.css' %}" rel="stylesheet" type="text/css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="{% static 'css/style_1.css' %}">
		
	</head>


	<body>
		
		<div id="site-content">
			<header class="site-header">
				<div class="container">
					<a href="{% url 'accounts:recipe' %}" id="branding" class="pull-left">
						<i class="icon-cupcake logo"></i>
						<h1 class="site-title">Sağlıklı Besinler Listesi</h1>
					</a>
					<!-- Default snippet for navigation -->
					<div class="main-navigation pull-right">
						<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
						<ul class="menu">
							<li class="menu-item current-menu-item"><a href="{% url 'user_login'  %}">Giriş Yap</a></li>
						</ul> <!-- .menu -->
					</div> <!-- .main-navigation -->

					<div class="mobile-navigation"></div>
				</div>
			</header> <!-- .site-header -->

			<main class="main-content">
				
				<div class="content">
					<div class="container">
						
						<h2 class="entry-title">Kronik böbrek hastaları nasıl beslenmelidir?</h2>
						<p>Böbrekler, su ve minerallerin (sodyum, potasyum ve fosfat) atılımını yeme ve içme alışkanlıklarına göre ayarlayarak su ve tuz dengesini sabit tutar. Vücutta çok fazla sodyum kalırsa, bu dokularda su tutulmasına yol açar. Çok fazla potasyum kardiyak aritmilere yol açabilir. Kronik böbrek hastalığında temel olarak dengeli beslenmeye dikkat edilmelidir. Günlük protein alımı sınırlandırılmalıdır. Potasyum, sodyum ve fosfat içeriği yüksek olan besinlerden kaçınılmalıdır. Bitkisel proteinler, hayvansal proteinlere tercih edilmelidir. </p>

						<h2 class="entry-title">Böbrek yetmezliğinde beslenme nasıl olmalı?</h2>
						<p>Böbrekler vücudun asit-baz dengesinde rol oynar. Daha az çalışırlarsa, yiyeceklerden gelen asitler daha az elimine edilir. Bu nedenle vücuttaki asit oranını yükselmek yerine alkali bir diyetin benimsenmesi tavsiye edilir. Tuz; ekmek, peynir, konserveler, işlenmiş etler, cipsler, krakerler ve hazır yemeklerde bulunmaktadır. Farkında olmadan yeterince tuz tüketimi yapılmaktadır. Bu sebeple yemeklere ekstra tuz eklenmemedir. Ayrıca fosfor ve potasyumdan zengin besinlerden kaçınmak gerekir.</p>

						<h2 class="entry-title">Yenilmemesi Gereken Yiyecekler Listesi:</h2>
						<p>✓ Beslenme programında önerilenden fazla süt, yoğurt, et, balık, tavuk, ekmek, sebze ve meyve tüketilmemelidir. <br>
							✓ İçeriği bilinmeyen çörek, kek, kurabiye, pasta börek, bisküvi, kraker<br>
							✓ Konserve yiyecekler, turşu, salamura, sucuk, pastırma, salam, sosis, zeytin vb.<br>
							✓ Kuruyemişler (badem, ceviz, fındık, fıstık vb.<br>
							✓ Kurutulmuş meyveler (kuru kayısı, kuru erik, pestil vb.).<br>
							✓ Çikolata, kakao katılmış hazır puding vs, tahin, pekmez, tahin helvası<br>
							✓ Et suyu ve hazır et suyu tabletler, et suyu ile yapılmış tüm yiyecekler<br>
							✓ Meşrubatlar (kola, gazoz, hazır meyve suları, sebze suları, kahve, neskafe, boza, maden suyu ve alkollü içecekler)<br>
							✓ Kepek ve kepek ekmeği. Tam tahıl buğdayı kullanılan unlu gıdalar<br>
							✓ Bulgur<br>
							✓ Kuru baklagiller (kuru fasulye, nohut, mercimek vb.)<br>
							✓ Soya fasulyesi, soya unu<br>
							✓ Pancar, bakla, pazı, bal kabağı (kış kabağı), enginar, börülce, ebegümeci, brüksel lahanası, karalahana, ıspanak, mantar, kereviz<br>
							✓ Muz, kavun, kivi, kayısı, avokado, Hindistan cevizi<br>
							✓ Hazır yiyecekler (hazır çorbalar, hazır tatlılar, mısır gevrekleri (cornflakes vb.), patates ve mısır cipsleri, hazır soslar, hazır köfte, hazır yemek harçları)<br>
							✓ Ev salçası<br>
							✓ Sakatatlar (karaciğer, böbrek, beyin, dil, dalak, yürek, işkembe)<br>
							✓ Yağda kızartılmış, kavrulmuş yiyecekler<br>
							✓ Tuz ve kabartma tozu eklenmiş tüm besinler</p>


						<div class="recipes-list">
							<article class="recipe">
								<figure class="recipe-image"><img src="{% static 'images/omlet.jpg' %}"></figure>
								<div class="recipe-detail">
									<h2 class="recipe-title"><a href="{% url 'accounts:single' %}">Biberli ve Peynirli Omlet</a></h2>
									<p>Atıştırmalık, Kahvaltı</p>
									<div class="recipe-meta">
										<span class="time"><img src="{% static 'images/icon-time.png' %}"> 10 min</span>
										<span class="calorie"><img src="{% static 'images/icon-pie-chart.png' %}"> 423 kcal</span>
									</div>
								</div>
							</article>
							<article class="recipe">
								<figure class="recipe-image"><img src="{% static 'images/bulgurlu_salata.jpg' %}"></figure>
								<div class="recipe-detail">
									<h2 class="recipe-title"><a href="{% url 'accounts:single' %}">Bulgurlu Yaz Salatası</a></h2>
									<p>Pratik Tarifler, Başlangıçlar & Aperatifler, Atıştırmalık</p>
									<div class="recipe-meta">
										<span class="time"><img src="{% static 'images/icon-time.png' %}"> 35 min</span>
										<span class="calorie"><img src="{% static 'images/icon-pie-chart.png' %}"> 268 kcal</span>
									</div>
								</div>
							</article>
							<article class="recipe">
								<figure class="recipe-image"><img src="{% static 'images/somon.jpg' %}"></figure>
								<div class="recipe-detail">
									<h2 class="recipe-title"><a href="{% url 'accounts:single1' %}">Baharatlı Somon Fileto ve Sote Roka Salatası</a></h2>
									<p>Ana yemek</p>
									<div class="recipe-meta">
										<span class="time"><img src="{% static 'images/icon-time.png' %}"> 60 min</span>
										<span class="calorie"><img src="{% static 'images/icon-pie-chart.png' %}"> 470 kcal</span>
									</div>
								</div>
							</article>
							<article class="recipe">
								<figure class="recipe-image"><img src="{% static 'images/salata.jpg' %}"></figure>
								<div class="recipe-detail">
									<h2 class="recipe-title"><a href="{% url 'accounts:single1' %}">Patates Salatası</a></h2>
									<p>Pratik Tarifler</p>
									<div class="recipe-meta">
										<span class="time"><img src="{% static 'images/icon-time.png' %}"> 120 min</span>
										<span class="calorie"><img src="{% static 'images/icon-pie-chart.png' %}"> 600 kcal</span>
									</div>
								</div>
							</article>
							<article class="recipe">
								<figure class="recipe-image"><img src="{% static 'images/tatlı.jpg' %}"></figure>
								<div class="recipe-detail">
									<h2 class="recipe-title"><a href="{% url 'accounts:single' %}">Armutlu Diyet Kek</a></h2>
									<p>Tatlı</p>
									<div class="recipe-meta">
										<span class="time"><img src="{% static 'images/icon-time.png' %}"> 60 min</span>
										<span class="calorie"><img src="{% static 'images/icon-pie-chart.png' %}"> 228 kcal</span>
									</div>
								</div>
							</article>
						</div>
					</div>
				</div>

			</main> <!-- .main-content -->
			
			<footer class="site-footer">
				<div class="container">
					<i class="icon-diet logo"></i>
					<nav class="footer-navigation">
					</nav>
					<div class="subscribe">
						<form action="#">
							<input type="text" placeholder="Enter your email to join newsletter...">
							<input type="submit" value="Subscribe">
						</form>
					</div>
					<div class="social-links">
						<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
						<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
						<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
					</div>
					<div class="colophon">
						<p>Copyright 2024. Designed by Enes Gür. Tüm Hakları Saklıdır</p>
					</div>
				</div>
			</footer>

		</div>

		

		<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
		<script src="{% static 'js/plugins.js' %}"></script>
		<script src="{% static 'js/app.js' %}"></script>
		
	</body>

</html>

accounts/templates/accounts/single.html
<!DOCTYPE html>
{% load static %}
<html lang="tr">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Diyetisyen | Tarifler</title>
		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|" rel="stylesheet" type="text/css">
		<link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'fonts/iconmoon.css' %}" rel="stylesheet" type="text/css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="{% static 'css/style_1.css' %}">
		
	</head>


	<body>
		
		<div id="site-content">
			<header class="site-header">
				<div class="container">
					<a href="{% url 'accounts:single' %}" id="branding" class="pull-left">
						<i class="icon-cupcake logo"></i>
						<h1 class="site-title">Böbrek Hastalığı Riskinizi Azaltmak İçin Besin Ve Takviyeler</h1>
					</a>
					<!-- Default snippet for navigation -->
					<div class="main-navigation pull-right">
						<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
						<ul class="menu">
							<li class="menu-item current-menu-item"><a href="{% url 'accounts:recipe' %}">Ana Sayfa</a></li>
							<li class="menu-item current-menu-item"><a href="{% url 'user_login'  %}">Giriş Yap</a></li>
						</ul> <!-- .menu -->
					</div> <!-- .main-navigation -->

					<div class="mobile-navigation"></div>
				</div>
			</header> <!-- .site-header -->

			<main class="main-content">
				
				<div class="content">
					<div class="container">
						
						<div class="row">
							<div class="col-md-4">
								<figure><img src="{% static 'images/omlet.jpg' %}"></figure>
							</div>
							<div class="col-md-7 col-md-offset-1">
								<h2 class="entry-title">Biberli ve Peynirli Omlet</h2>
								<div class="recipe-meta">
									<span class="time"><img src="{% static 'images/icon-time.png' %}"> 10 min</span>
									<span class="calorie"><img src="{% static 'images/icon-pie-chart.png' %}"> 423 kcal</span>
								</div>
								<div class="ingredient">
									<h3>Malzemeler</h3>
									<table>
										<tr>
											<td><strong>120 g</strong></td> 
											<td>Krem Edema peyniri (40 % yağ oranı)</td>
										</tr>
										<tr>
											<td><strong>4 Adet</strong></td> 
											<td>Çırpılmış Yumurta</td>
										</tr>
										<tr>
											<td><strong>40 g</strong></td> 
											<td>Zeytinyağı</td>
										</tr>
										<tr>
											<td><strong>5 g</strong></td> 
											<td>Karabiber</td>
										</tr>
										<tr>
											<td><strong>1 Adet</strong></td> 
											<td>Doğranmış Soğan</td>
										</tr>
										<tr>
											<td><strong>2 Adet</strong></td> 
											<td>Kavrulmuş Sivri Biber</td>
										</tr>
										<tr>
											<td><strong>250 g</strong></td> 
											<td>Kızarmış Ekmek</td>
										</tr>
									</table>
								</div>
								<p>Yapılışı:</p>
								<p>Zeytinyağını yapışmaz bir tavaya koyup ısıtın. Soğanları yumurtalarla karıştırdıktan sonra tavaya koyun. Baharatları ve biberi ekleyin. Bir kaç dakika pişirdikten sonra omleti ters çevirin. Krem peyniri omletin üzerine yayıp 1 dakika daha pişirin. Omleti ikiye katlayıp hemen servis edin. Yanına kavrulmuş biber ve kızarmış ekmek koyun.</p>
							</div>
						</div>
						
					</div>
				</div>

			</main> <!-- .main-content -->
			
			<footer class="site-footer">
				<div class="container">
					<i class="icon-cupcake logo"></i>
					<nav class="footer-navigation">
					</nav>
					<div class="subscribe">
					</div>
					<div class="social-links">
						<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
						<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
						<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
					</div>
					<div class="colophon">
						<p>Copyright 2024. Designed by Enes Gür. Tüm Hakları Saklıdır</p>
					</div>
				</div>
			</footer>

		</div>

		

		<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
		<script src="{% static 'js/plugins.js' %}"></script>
		<script src="{% static 'js/app.js' %}"></script>
		
	</body>

</html>